# -*- coding: utf-8 -*-
"""Tutorial3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ihqr7XxD5D_1wh9EgLHJwB72wDxa5N2h

# Tutorial 3

## Setup
"""

# Installing Preliz if necessary
!pip install preliz

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import arviz as az
import matplotlib.pyplot as plt
import pymc as pm
import numpy as np
import pandas as pd
from scipy import stats
import seaborn as sns

from google.colab import files
import preliz as pz

# Random generator for reproducible simulations
rng = np.random.default_rng(123)

plt.rcParams["figure.dpi"] = 130
plt.rcParams["figure.figsize"] = (7, 4)

az.style.use("arviz-darkgrid")
sns.set_style("darkgrid")

"""## Load data


"""

# Load the dataset
uploaded = files.upload()

filename = list(uploaded.keys())[0]

df = pd.read_csv(filename)
df.head()

# Create the binary Biotechnology variable
# biotech = 1 if "Biotechnology" appears anywhere in category_list, 0 otherwise

df["category_list"] = df["category_list"].astype(str).str.strip()

df["biotech"] = (
    df["category_list"]
    .str.contains("Biotechnology", case=False, na=False)
    .astype(int)
)

df[["category_list", "biotech"]].head()

# Plot the Biotechnology variable
counts = df["biotech"].value_counts().sort_index()

plt.figure(figsize=(5, 4))
bars = plt.bar(counts.index, counts.values)

plt.xticks([0, 1], ["0 = not Biotechnology", "1 = Biotechnology"])
plt.xlabel("biotech")
plt.ylabel("Count")
plt.title("Distribution of Biotechnology startups")

for i, v in enumerate(counts.values):
    plt.text(i, v + max(counts.values)*0.01, f"{int(v)}", ha="center")

plt.show()

# Basic summaries
data = df["biotech"].to_numpy()

n = len(data)
k = data.sum()
theta_hat = data.mean()

print(f"Number of startups: {n}")
print(f"Number of Biotechnology startups: {k}")
print(f"Observed Biotechnology rate: {theta_hat:.4f}")

"""# Modeling Biotechnology company category rate"""

# Choosing a prior
# Let's say I belive 10% of startups belong to the "Biotechnology" category.
# I can choose a "weak" prior Beta(2,18) - I saw alpha-1 successes & beta-1 failures
# or I can choose a "strong" prior Beta(10, 90)

# Weaker prior (but still informative)
a = 2
b = 18

# # Stronger prior - narrower distribution
# a = 10
# b = 90

# # Flap prior (no prior knowledge)
# a = 1
# b = 1

pz.Beta(alpha=a, beta=b).plot_interactive()

"""### PyMC"""

# coords - naming our data
coords = {"startup": np.arange(len(data))}

# First PyMC model
with pm.Model(coords=coords) as biotech_model:
    theta = pm.Beta("theta", alpha=a, beta=b)
    y = pm.Bernoulli("y", p=theta, observed=data, dims='startup')

    idata = pm.sample(1000, chains=4, random_seed=17)

pm.model_to_graphviz(biotech_model)

"""#### Inference Data Object"""

idata

"""#### Posterior"""

#we can save an xarray of the posterior information
posterior = idata.posterior.theta
posterior.shape #and see that the shape is 1000 draws for 4 chains

#we can also convert the information into a numpy array
posterior_np = posterior.to_numpy()
posterior_np

"""#### Analyzing the Posterior"""

az.plot_trace(idata, compact=False)

"""#### Means of Chains"""

ms = idata.posterior.mean(dim = 'draw')
print(f'The means of the 4 chains are: {np.round(ms.theta.to_numpy(), 3)}')

"""#### comparing with our analytical results

"""

#comparing with our analytical results
alpha_prior = 2
beta_prior = 18
theta_grid = np.linspace(0, 1, 1000)

posterior_analytical = pz.Beta(alpha_prior + k, beta_prior + n - k).pdf(theta_grid)
plt.plot(theta_grid, posterior_analytical, color='red')

# Compare PyMC posterior samples with analytical posterior

# PyMC posterior samples
posterior_samples = az.extract(idata, var_names=["theta"]).to_numpy()

plt.figure(figsize=(8, 5))

# Analytical posterior
plt.plot(
    theta_grid,
    posterior_analytical,
    color="red",
    linewidth=1,
    label="Analytical posterior"
)

# PyMC sampled posterior
az.plot_kde(
    posterior_samples,
    label="PyMC posterior samples"
)


plt.xlabel(r"$\theta$ = probability of Biotechnology startup")
plt.ylabel("Density")
plt.title("PyMC posterior vs analytical Beta posterior")
plt.legend()
plt.show()

"""#### Effect of number of samples (draws)

"""

# Previous Model with 1000 posterior draws per chain
az.plot_trace(idata, compact=False)

ms = idata.posterior.mean(dim="draw")
print(f"The means of the 4 chains are: {np.round(ms.theta.to_numpy(), 4)}")

# Same model with 10000 posterior draws per chain

with pm.Model(coords=coords) as biotech_model_10000:
    theta = pm.Beta("theta", alpha=a, beta=b)
    y = pm.Bernoulli("y", p=theta, observed=data, dims="startup")

    idata10000 = pm.sample(10000, chains=4, random_seed=17)

# Trace plot
az.plot_trace(idata10000, compact=False)
plt.show()

ms = idata10000.posterior.mean(dim="draw")
print(f"The means of the 4 chains are: {np.round(ms.theta.to_numpy(), 4)}")

# Posterior samples from the first model
posterior = idata.posterior.theta
posterior

# Combine the 4 chains in the trace plot - we don't usually do it, just for you to see the option
az.plot_trace(idata, combined=True)

# Overall posterior mean across all chains and draws
m = idata.posterior.mean()

print(f"The total mean of the posterior samples is: {np.round(m.theta.to_numpy(), 4)}")

# Get all posterior samples as one combined object

posterior_samples = az.extract(idata)
posterior_samples

# Randomly sample 3500 values from the posterior samples

theta_samples_3500 = az.extract(idata, var_names=["theta"], num_samples=3500)
theta_samples_3500

"""Increasing the number of draws does not change the model.
It only gives us more samples from the same posterior distribution.

With more draws, the sampled approximation of the posterior becomes more stable.
The chains should look more similar, and posterior summaries such as the mean and mode should fluctuate less.

#### Posterior plot and HDI
"""

az.plot_posterior(idata)

az.summary(idata, kind="stats")

# Or az.summary(idata) if you want more than the mean, sd and HDI (we'll learn about it later)

"""---

# Frequentist Statistics

## MLE
"""

# Basic summaries (reminder)
data = df["biotech"].to_numpy()

n = len(data)
k = data.sum()
theta_hat_analytic = k / n


print("Number of startups n", n)
print("Number of Biotechnology startups k", k)
print("Observed Biotechnology rate k/n", theta_hat_analytic)

# The unknown parameter theta is the probability that a startup is in Biotechnology.

"""#### Analytical MLE for the Binomial model"""

# For a Binomial model, the MLE has a simple closed-form solution:
#   theta_hat_MLE = k / n
#
# In this dataset:
#   theta_hat_MLE = number of Biotechnology startups / total startups

theta_hat_analytic = k / n

print("Analytical MLE for the Binomial model:")
print(f"theta_hat = k/n = {k}/{n} = {theta_hat_analytic}")

"""#### Log-likelihood: same MLE, better numerical behavior

"""

# With large datasets, multiplying many probabilities can produce extremely small numbers.
# Therefore, likelihood values can become numerically unstable.
#
# We usually use log-likelihood instead:
#   log-likelihood = log likelihood
#
# Since log is monotonic:
#   the theta that maximizes likelihood also maximizes log-likelihood.

from scipy import stats, special, optimize

# Candidate theta values for plotting the likelihood/log-likelihood curve
theta_grid = np.linspace(0.001, 0.999, 999)

def binomial_likelihood(theta, k, n):
    """
    Binomial likelihood: probability of observing k Biotechnology startups
    out of n startups, for each candidate theta.
    """
    return stats.binom.pmf(k, n=n, p=theta)


def binomial_loglikelihood(theta, k, n):
    """
    Binomial log-likelihood up to an additive constant.

    We omit log(n choose k), because it does not depend on theta.
    Omitting it does not change the MLE.
    """
    theta = np.asarray(theta, dtype=float)
    return special.xlogy(k, theta) + special.xlog1py(n - k, -theta)

loglik_grid = binomial_loglikelihood(theta_grid, k, n)

plt.figure()
plt.plot(theta_grid, loglik_grid, label="Log-likelihood")
plt.axvline(theta_hat_analytic, linestyle="--",
            label=f"Analytic MLE = {theta_hat_analytic:.4f}")
plt.xlabel(r"$\theta$")
plt.ylabel("log-likelihood")
plt.title("Log-likelihood: same maximum, different scale")
plt.legend()
plt.show()


# This is a useful place to say:
#   We did not change the statistical question.
#   We only changed the numerical scale.
#   The maximum is in the same place.

"""#### Numerical optimization"""

# A more general computational approach
# scipy.optimize minimizes functions.
# Since MLE requires maximizing log-likelihood, we minimize the negative log-likelihood.

def negative_binomial_loglikelihood(theta, k, n):
    """
    Negative log-likelihood for numerical optimization.
    """
    return -binomial_loglikelihood(theta, k, n)


opt_result = optimize.minimize_scalar(
    negative_binomial_loglikelihood,
    bounds=(0.001, 0.999),
    args=(k, n),
    method="bounded"
)

theta_hat_optim = opt_result.x

print("Numerical optimization MLE for the Binomial model:")
print(f"theta_hat = {theta_hat_optim:.4f}")

comparison = pd.DataFrame({
    "Method": ["Analytic k/n", "Optimization"],
    "MLE estimate": [theta_hat_analytic, theta_hat_optim],
})

comparison["Absolute difference from analytic MLE"] = np.abs(
    comparison["MLE estimate"] - theta_hat_analytic
)

comparison


# The methods should give nearly the same answer.
# This links:
#   1. A formula: k/n
#   2. A general computational method: optimization

"""#### Sampling distribution of the MLE

"""

# Frequentist uncertainty is about repeated sampling.
#
# The true theta is treated as fixed.
# The data would change if we repeated the study.
# Therefore, the estimate theta_hat = k/n would also change.
#
# Since we do not know the true theta, we use the observed MLE as a plausible value
# for demonstration.

assumed_true_theta = theta_hat_analytic
sample_size = n
num_simulated_datasets = 5000

simulated_k = rng.binomial(
    n=sample_size,
    p=assumed_true_theta,
    size=num_simulated_datasets
)

simulated_theta_hat = simulated_k / sample_size

plt.figure()
plt.hist(simulated_theta_hat, bins=30, edgecolor="black")
plt.axvline(assumed_true_theta, color='black',  linestyle="--", label=f"Assumed true theta = {assumed_true_theta:.4f}")
plt.xlabel(r"$\hat{\theta} = k/n$")
plt.ylabel("Number of simulated datasets")
plt.title("Sampling distribution of the MLE")
plt.legend()
plt.show()

sampling_summary = pd.DataFrame({
    "Quantity": ["Assumed true theta", "Mean of simulated theta_hat", "SD of simulated theta_hat"],
    "Value": [
        assumed_true_theta,
        simulated_theta_hat.mean(),
        simulated_theta_hat.std(ddof=1)
    ],
})

sampling_summary


# Even if theta is fixed, the estimate changes across repeated datasets.
# That variability is the sampling distribution of the estimator.

"""## CI"""

# Confidence interval by Binomial inversion

# Logic:
#   For each candidate theta, ask:
#     Would our observed number of Biotechnology startups be too extreme
#     if this theta were true?
#
# If the observed k is not too extreme under theta, we keep theta.
# The kept theta values form the confidence interval.

alpha = 0.05
k_obs = k
n_obs = n

theta_candidates = np.linspace(0.001, 0.999, 999)
accepted = []

for theta in theta_candidates:
    # Probability of observing k_obs or fewer acquired startups
    lower_tail = stats.binom.cdf(k_obs, n=n_obs, p=theta)

    # Probability of observing k_obs or more acquired startups
    upper_tail = 1 - stats.binom.cdf(k_obs - 1, n=n_obs, p=theta)

    # Keep theta values for which the observed result is not in the extreme tails
    if lower_tail > alpha / 2 and upper_tail > alpha / 2:
        accepted.append(theta)

ci_lower = min(accepted)
ci_upper = max(accepted)

print(f"Observed MLE: {theta_hat_analytic:.4f}")
print(f"Approximate 95% CI by Binomial inversion: [{ci_lower:.4f}, {ci_upper:.4f}]")


# Plot likelihood together with CI limits.
plt.figure()
plt.plot(theta_candidates, binomial_likelihood(theta_candidates, k_obs, n_obs), label="Likelihood")
plt.axvline(theta_hat_analytic, linestyle="--", label=f"MLE = {theta_hat_analytic:.4f}")
plt.axvline(ci_lower, linestyle=":", label=f"CI lower = {ci_lower:.4f}")
plt.axvline(ci_upper, linestyle=":", label=f"CI upper = {ci_upper:.4f}")
plt.xlabel(r"$\theta$ = probability that a startup belongs to Biotechnology")
plt.ylabel(r"$P(k_{obs} \mid n, \theta)$")
plt.title("MLE and confidence interval for Biotechnology startups rate")
plt.legend()
plt.show()


# Important wording:
#   Incorrect: There is a 95% probability that theta is inside this interval.
#   Correct: If we repeated the full procedure many times, about 95% of the intervals
#            would contain the true theta, assuming the model is correct.

"""#### Coverage simulation for the CI procedure

"""

# Long-run interpretation of confidence intervals.
# We repeat the experiment many times:
#   1. Generate a dataset from an assumed true theta
#   2. Compute the CI for that dataset
#   3. Check whether the CI contains the assumed true theta
# If the method has approximately 95% coverage, around 95% of intervals
# should contain the true theta.


def binomial_ci_by_inversion(k_obs, n_obs, alpha=0.05, grid_size=999):
    """
    Approximate two-sided Binomial confidence interval by grid inversion.

    This function is written for teaching clarity rather than computational speed.
    """
    theta_candidates = np.linspace(0.001, 0.999, grid_size)
    accepted = []

    for theta in theta_candidates:
        lower_tail = stats.binom.cdf(k_obs, n=n_obs, p=theta)
        upper_tail = 1 - stats.binom.cdf(k_obs - 1, n=n_obs, p=theta)

        if lower_tail > alpha / 2 and upper_tail > alpha / 2:
            accepted.append(theta)

    if len(accepted) == 0:
        return np.nan, np.nan

    return min(accepted), max(accepted)


true_theta_for_coverage = theta_hat_analytic
n_for_coverage = n
num_experiments = 300

coverage_records = []

for experiment_id in range(num_experiments):
    k_sim = rng.binomial(n=n_for_coverage, p=true_theta_for_coverage)
    theta_hat_sim = k_sim / n_for_coverage
    lo, hi = binomial_ci_by_inversion(k_sim, n_for_coverage, alpha=0.05)
    contains_true = lo <= true_theta_for_coverage <= hi

    coverage_records.append({
        "experiment": experiment_id,
        "k": k_sim,
        "theta_hat": theta_hat_sim,
        "ci_lower": lo,
        "ci_upper": hi,
        "contains_true": contains_true,
    })

coverage_df = pd.DataFrame(coverage_records)
coverage_rate = coverage_df["contains_true"].mean()

print(f"Estimated coverage over {num_experiments} experiments: {coverage_rate:.3f}")


# Plot a subset of intervals for readability.
plot_df = coverage_df.head(80).copy()

plt.figure(figsize=(8, 6))
for _, row in plot_df.iterrows():
    color = "black" if row["contains_true"] else "gray"
    plt.plot([row["ci_lower"], row["ci_upper"]], [row["experiment"], row["experiment"]], color=color)
    plt.plot(row["theta_hat"], row["experiment"], marker="o", color=color, markersize=3)

plt.axvline(true_theta_for_coverage, linestyle="--", label=f"Assumed true theta = {true_theta_for_coverage:.4f}")
plt.xlabel(r"$\theta$")
plt.ylabel("Repeated experiment index")
plt.title("Confidence intervals across repeated experiments")
plt.legend()
plt.show()


#   - Each horizontal line is one interval from one simulated experiment.
#   - The vertical dashed line is the assumed true theta.
#   - Some intervals miss it.
#   - The confidence level describes the long-run behavior of the method.

